name: package-firmware   #cpt-firmware-cn10k_<version>_arm64

on:
  push:
  schedule:
    - cron: "0 0 * * 1"
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write

jobs:
  ubuntu-cn10k-package:
    name: ubuntu-cn10k-arm64
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Extract version details
        id: version
        run: |
          mkdir -p "${PWD}/artifacts"
          git tag --points-at HEAD > /tmp/tags
          [ -s /tmp/tags ] && PKG_POSTFIX= || PKG_POSTFIX=-devel
          echo "PKG_VERSION_NAME=`cat VERSION`" >> "${PWD}/artifacts/env"
          echo "PKG_POSTFIX=${PKG_POSTFIX}" >> "${PWD}/artifacts/env"
      - name: Generate CPT package
        run: |                                                                                          
            source /artifacts/env                                                                           
            mkdir -p "${PWD}/install/lib/firmware/mrvl/"
            cp -r ${PWD}/files/ ${PWD}/install/lib/firmware/mrvl/
            mkdir -p "${PWD}/install/DEBIAN"
            cd "${PWD}/install/"
            echo 'Package: cpt-cn10k'$PKG_POSTFIX >> DEBIAN/control                                         
            echo 'Version: '$PKG_VERSION_NAME >> DEBIAN/control                                           
            echo "Maintainer: Jerin Jacob (jerinj@marvell.com)" >> DEBIAN/control
            echo "Architecture: arm64" >> DEBIAN/control
            echo "Description: DPU Accelerator offload for Marvell Octeon 10" >> DEBIAN/control
            cd -
            mv "${PWD}/install" "${PWD}/cpt-cn10k_arm64"
            dpkg --build "${PWD}/cpt-cn10k_arm64"
            cp "${PWD}/cpt-cn10k_arm64.deb" /artifacts/.
      # Export version details
      # Delete existing release
      # Release package for own repo
      # Dispatch package update event for packages repo            
                 